### ISSUE TITLE
crypto-js vs react-native-crypto-js

### ISSUE THREAD

**Issue by pedrouid** [imchintan/react-native-crypto-js#2]
What are the main differences between this library and the original?

**Comment by paolospag** [comment]
@pedrouid I'm as confused as you are...
What's different than the original library?

Seeing **List of Algorithms**(https://github.com/imchintan/react-native-crypto-js#list-of-algorithms), in this library only a few algorithms are implemented?

@imchintan can you give us explanations?

**Comment by pcowgill** [comment]
@pedrouid Were you comparing this with `crypto-js` on npm or the `crypto-js` linked to in the README that only seems to be available as a Google Code Archive?

It seems like the main two differences between this lib and the `crypto-js` on npm are:

1) This library has fewer algorithms implemented
2) `crypto-js` was built for node or the browser, so it may have some dependencies that don't work in a React Native env

Is that your understanding as well?
