### ISSUE TITLE
TypeError: Cannot read property 'salt' of undefined

### ISSUE THREAD

**Issue by kushagra27** [imchintan/react-native-crypto-js#4]
Facing this error while using AES decrypt
it says c.salt is not defined
![Screenshot from 2019-05-24 12-13-10](https://user-images.githubusercontent.com/30297338/58307801-6844c700-7e1d-11e9-8752-ee63ecab2c0f.png)

Below is the code I am using
![Screenshot from 2019-05-24 12-17-29](https://user-images.githubusercontent.com/30297338/58307990-ebfeb380-7e1d-11e9-855f-6df697baac53.png)

**Comment by imchintan** [comment]
@kushagra27 Thanks for reporting issues. Can you please provide the detail of React Native version?

**Comment by kushagra27** [comment]
I'm using React Native 0.59.8
But I seem to have figured it out. There was some problem with the AsyncStorage.
Anyway thanks for your help

**Comment by feruzm** [comment]
What issue was it @kushagra27 ?
